### ISSUE TITLE
Only one Miller-Rabin test?

### ISSUE THREAD

**Issue by matlink** [fardog/primebot#5]
If it returns true, then the number is prime with probability 1 - 1/4
https://github.com/fardog/primebot/blob/master/generator_probablyprime.go#L54

**Comment by fardog** [comment]
@matlink is this true for any number less than 2 ^ 64 - 1? my read on the docs was that this was a 100% accurate test for any number smaller than that (iirc it does more than miller-rabin) but if my read on the docs is wrong then it definitely needs correction. do you have better info?

**Comment by fardog** [comment]
fwiw this was taken from [the docs](https://golang.org/pkg/math/big/#Int.ProbablyPrime)

>  ProbablyPrime is 100% accurate for inputs less than 2⁶⁴. See Menezes et al., Handbook of Applied Cryptography, 1997, pp. 145-149, and FIPS 186-4 Appendix F for further discussion of the error probabilities. 

but i'm super-not mathematically versed, and it's possible that my read is naive

**Comment by matlink** [comment]
OKay you're right, I didn't read the docs. Usually we test primality for numbers of more than thousand bits, that's why your usage is confusing :)
